/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_liambloom_checker_internal_Native */

#ifndef _Included_dev_liambloom_checker_internal_Native
#define _Included_dev_liambloom_checker_internal_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_liambloom_checker_internal_Native
 * Method:    changeDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_liambloom_checker_internal_Native_changeDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
